audit_header: false
title: "The Pacific Northwest's Best Real Estate Training"
description: Chad Storey, a top Real Estate Agent in The Pacific Northwest, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Real Estate Events
    url: https://www.eventbrite.com/o/century-21-northwest-6547788911
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Chad Storey
  title:
  license_number:
  about_markdown: |
    In 2003 Chad started flipping houses while still working in the tech industry. Chad got his real estate license that year as well and he and his tech industry friends started to marry their tech industry knowledge with real estate. Chad actually built an MLS for foreclosures and sold that company. Chad realized there was more money to be made in real estate than staying in the tech industry and that the "smart agents" in the area didn't know about technology. Chad became a full-time independent agent in 2005 and by 2015 he was recruited by Century 21 to run a brokerage for them. Now in 2019 C21 NW is at 160 agents, 7 locations and paid out $10 Million GCI last year.
  market: The Pacific Northwest
  brand: Century21 Northwest
  brokerage:
  address: 121 Lake Street South, Suite 201, Kirkland, WA 98033
  phone: 425-250-3301
  phone_type:
  phone2:
  phone2_type:
  email: recruiting@c21nwr.com
  url: http://www.c21nwr.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/C21NWRealty/
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'The Pacific Northwest Real Estate Podcast with Chad Storey'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the The Pacific Northwest Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional The Pacific Northwest Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in The Pacific Northwest, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Chad Storey'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: The Pacific Northwest Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#BEAE89'
  theme_color: '#404041'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
